# Generated by Django 4.2.6 on 2023-10-11 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('Local_Assembly', models.CharField(max_length=250)),
                ('Nationality', models.CharField(max_length=100)),
                ('State_of_Origin', models.CharField(max_length=100)),
                ('Local_Government_Area', models.CharField(max_length=200)),
                ('Are_you_a_pastor', models.BooleanField(default=False)),
                ('will_you_be_camping', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 2, 59, 51, 24689, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 2, 59, 51, 26691, tzinfo=datetime.timezone.utc))),
                ('Attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.attendees')),
            ],
        ),
    ]
