# Generated by Django 4.1.7 on 2023-10-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendees",
            old_name="State_of_Origin",
            new_name="State_of_Residence",
        ),
        migrations.AlterField(
            model_name="attendees",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 18, 13, 52, 1, 555552, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="volunteers",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 18, 13, 52, 1, 556065, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
