# Generated by Django 4.1.7 on 2023-10-24 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_state_of_origin_attendees_state_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='Volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 2, 30, 4, 508327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 2, 30, 4, 508327, tzinfo=datetime.timezone.utc)),
        ),
    ]
