# Generated by Django 4.1.7 on 2023-10-24 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_volunteers_volunteer_alter_attendees_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 22, 55, 44, 405748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='Attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='homepage.attendees'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 22, 55, 44, 405748, tzinfo=datetime.timezone.utc)),
        ),
    ]
