# Generated by Django 4.1.7 on 2023-10-25 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_attendees_created_alter_volunteers_attendee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=250)),
                ('Request', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 10, 25, 3, 9, 27, 863310, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='attendees',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 3, 9, 27, 863310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 3, 9, 27, 863310, tzinfo=datetime.timezone.utc)),
        ),
    ]
