# Generated by Django 4.1.7 on 2023-11-15 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_attendees_uid_alter_attendees_are_you_a_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 19, 16, 37, 744303, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 19, 16, 37, 746399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 19, 16, 37, 745398, tzinfo=datetime.timezone.utc)),
        ),
    ]
