# Generated by Django 4.1.7 on 2023-11-15 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_attendees_created_alter_prayerrequest_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 20, 47, 23, 256717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 20, 47, 23, 256717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 20, 47, 23, 256717, tzinfo=datetime.timezone.utc)),
        ),
    ]
