# Generated by Django 4.1.7 on 2023-12-09 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_specialcard_alter_attendees_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcard',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 17, 23, 47, 403562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 17, 23, 47, 403562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 17, 23, 47, 403562, tzinfo=datetime.timezone.utc)),
        ),
    ]
