# Generated by Django 4.1.7 on 2023-12-09 20:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_specialcard_position_alter_prayerrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 20, 4, 23, 878188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 20, 4, 23, 878188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 20, 4, 23, 878188, tzinfo=datetime.timezone.utc)),
        ),
    ]
