# Generated by Django 4.1.7 on 2023-12-09 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_volunteers_uid_specialcard_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 17, 47, 165117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 17, 47, 165117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 17, 47, 165117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='InHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Enter your department name')),
                ('brethren', models.BooleanField(default=False, verbose_name='Are you an inhouse brethen?')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inhouse', to='homepage.attendees')),
            ],
        ),
    ]
