# Generated by Django 4.1.7 on 2023-12-10 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_prayerrequest_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialcard',
            old_name='position',
            new_name='church',
        ),
        migrations.RemoveField(
            model_name='specialcard',
            name='pastor',
        ),
        migrations.AddField(
            model_name='specialcard',
            name='title',
            field=models.CharField(default='layers of truth', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 58, 29, 337991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='specialcard',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 58, 29, 337991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 58, 29, 337991, tzinfo=datetime.timezone.utc)),
        ),
    ]
