# Generated by Django 4.1.7 on 2023-11-15 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0010_alter_attendees_created_alter_prayerrequest_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='attendance.createattendance')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.attendees')),
            ],
        ),
    ]
